[package]
authors = ["Harry Brundage <harry@gadget.dev>"]
edition = "2021"
name = "silo"
description = "A background job server on top of object storage"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.14", features = ["derive"] }
slatedb = "0.8.2"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
thiserror = "1.0"
anyhow = "1"
serde_json = "1.0"
uuid = { version = "1.9", features = ["v4", "fast-rng", "serde"] }
rkyv = { version = "0.7", features = ["validation"] }
bytecheck = "0.6"
bytes = "1"
crossbeam-skiplist = "0.1"
tonic = { version = "0.12", features = ["transport"] }
prost = "0.13"
prost-types = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-perfetto = "0.1"
silo-macros = { path = "silo-macros" }
tokio-stream = "0.1"
etcd-client = { version = "0.13", default-features = false, features = ["tls"] }
tracing-opentelemetry = "0.27"
opentelemetry = { version = "0.26" }
opentelemetry_sdk = { version = "0.26", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.26", features = ["http-json", "trace"] }
usdt = "0.6.0"
tempfile = "3"

[dev-dependencies]
turmoil = { path = "/Users/airhorns/Code/turmoil" }
rand = "0.8"
rand_chacha = "0.3"
async-stream = "0.3"
hyper-util = "0.1"
hyper = "1"
tower = "0.4"
criterion = { version = "0.5", features = ["async_tokio"] }

[build-dependencies]
tonic-build = "0.12"
protoc-bin-vendored = "3.0"

[profile.release]
debug = 1     # debug info with line tables only for profiling
strip = false # do not strip symbols for profiling

[[bench]]
name = "job_shard_throughput"
harness = false
