name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux binaries
    runs-on: ubuntu-latest-l
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-test-env
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: Swatinem/rust-cache@v2

      - name: Build release binaries
        shell: bash
        run: cargo build --release

      - name: Upload silo binary
        uses: actions/upload-artifact@v4
        with:
          name: silo-linux-x86_64
          path: target/release/silo
          if-no-files-found: error

      - name: Upload silo-bench binary
        uses: actions/upload-artifact@v4
        with:
          name: silo-bench-linux-x86_64
          path: target/release/silo-bench
          if-no-files-found: error

      - name: Upload silo-sim binary
        uses: actions/upload-artifact@v4
        with:
          name: silo-sim-linux-x86_64
          path: target/release/silo-sim
          if-no-files-found: error
